language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt

script: coverage run --source='.' manage.py test

before_install:
      - pip install codecov
after_success:
      - codecov
